[env:esp32-pico-d4]
platform = espressif32@6.7.0
board = pico32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
build_flags =
  -DCORE_DEBUG_LEVEL=3
monitor_filters =
  esp32_exception_decoder
  time

; Voor OTA upload vanaf PlatformIO:
; upload_protocol = espota
; upload_port = <ip-van-je-esp32>
; upload_flags = --auth=<ota-password>
