[platformio]
default_envs = esp32-pico-d4-ota

[env:esp32-pico-d4-base]
platform = espressif32@6.7.0
board = pico32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
build_flags =
  -DCORE_DEBUG_LEVEL=3
monitor_filters =
  esp32_exception_decoder
  time

[env:esp32-pico-d4-ota]
extends = env:esp32-pico-d4-base
upload_protocol = espota
upload_port = 192.168.1.175
upload_flags =
  --auth=change-me
  --timeout=60

[env:esp32-pico-d4-serial]
extends = env:esp32-pico-d4-base
upload_protocol = esptool
upload_port = /dev/cu.usbserial-8D52260C38

[env:esp32-pico-d4]
extends = env:esp32-pico-d4-ota
