[platformio]
default_envs = esp32-pico-d4-ota

[env:esp32-pico-d4-base]
platform = espressif32@6.7.0
#board = pico32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  knolleary/PubSubClient@^2.8
build_flags =
  -DCORE_DEBUG_LEVEL=3
monitor_filters =
  esp32_exception_decoder
  time

[env:esp32-pico-d4-ota]
extends = env:esp32-pico-d4-base
upload_protocol = espota
upload_port = 192.168.1.176
upload_flags =
  --auth=change-me
  --timeout=60

[env:esp32-pico-d4-serial]
extends = env:esp32-pico-d4-base
upload_protocol = esptool
upload_port = /dev/cu.usbserial-8D52260C38

[env:esp32-pico-d4]
extends = env:esp32-pico-d4-ota

[env:m5stack-core2-base]
platform = espressif32@6.7.0
board = m5stack-core2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  knolleary/PubSubClient@^2.8
build_flags =
  -DCORE_DEBUG_LEVEL=3
monitor_filters =
  esp32_exception_decoder
  time

[env:m5stack-core2-ota]
extends = env:m5stack-core2-base
upload_protocol = espota
upload_port = 192.168.1.176
upload_flags =
  --auth=change-me
  --timeout=60

[env:m5stack-core2-serial]
extends = env:m5stack-core2-base
upload_protocol = esptool

[env:m5stack-core2]
extends = env:m5stack-core2-ota

[env:esp32dev-base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  knolleary/PubSubClient@^2.8
build_flags =
  -DCORE_DEBUG_LEVEL=3
monitor_filters =
  esp32_exception_decoder
  time

[env:esp32dev-ota]
extends = env:esp32dev-base
upload_protocol = espota
upload_port = 192.168.1.175
upload_flags =
  --auth=change-me
  --timeout=60

[env:esp32dev-serial]
extends = env:esp32dev-base
upload_protocol = esptool

[env:esp32dev]
extends = env:esp32dev-ota
